# SERVER CONFIGURATION
server:
    servlet:
        context-path: /
    port: 8080
    shutdown: "graceful"
    compression:
        enabled: true
        mime-types:
            - text/html
            - text/xml
            - text/plain
            - text/css
            - text/javascript
            - application/javascript
            - application/json
        min-response-size: 1024
    undertow:
        threads:
            worker: 64
            io: 4

# ACTUATOR CONFIGURATION
management:
    endpoint:
        health:
            show-details: never
    endpoints:
        web:
            base-path: /
            exposure:
                include: health,circuitbreakers,circuitbreakerevents,ratelimiters,ratelimiterevents,bulkheads,bulkheadevents

# DATABASE CONFIGURATIONS
database:
    url: ${DATABASE_URL:localhost:3306}
    schema-name: ${DATABASE_SCHEMA:ecommerce}
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:root}

# SPRING CONFIGURATION
spring:
    application:
        name: @project.name@
        version: @project.version@
    main:
        banner-mode: "off"
    web:
        resources:
            add-mappings: false
    mvc:
        throw-exception-if-no-handler-found: true
        favicon:
            enabled: false
    metrics:
        web:
            server:
                auto-time-requests: true

# CODECS CONFIGURATION
    codec:
        max-in-memory-size: 1MB

# SPRING VIRTUAL THREADS FOR JAVA 21
    threads:
        virtual:
            enabled: true

# SPRING DATA JPA CONFIGURATION
    datasource:
        url: jdbc:mysql://${database.url}/${database.schema-name}?serverTimezone=UTC&characterEncoding=UTF-8&rewriteBatchedStatements=true
        username: ${database.username}
        password: ${database.password}
        hikari:
            auto-commit: false
            connection-timeout: 10000 # milliseconds (10 seconds)
            max-lifetime: 600000      # milliseconds (10 minutes)
            maximum-pool-size: 20     # max connections per replica
            minimum-idle: 10          # min connections per replica
            idle-timeout: 300000      # milliseconds (5 minutes)
            pool-name: ${spring.application.name}
    jpa:
        open-in-view: false
        show-sql: false
        hibernate:
            ddl-auto: none
        properties:
            "[hibernate.dialect.storage_engine]": innodb
            "[hibernate.generate_statistics]": false
            "[hibernate.connection.provider_disables_autocommit]": true
            "[hibernate.jdbc.batch_size]": 20
            "[hibernate.order_inserts]": true
            "[hibernate.order_updates]": true

# SPRING CLOUD CONFIGURATION
    cloud:
        stream:
            kafka:
                binder:
                    auto-create-topics: true
            bindings:
                authorizationOrderEvents-out-0:
                    destination: authorization-order-events
                    binder: ecommerce
            binders:
                ecommerce:
                    type: kafka
                    environment:
                        spring:
                            cloud:
                                stream:
                                    kafka:
                                        binder:
                                            brokers: ${KAFKA_BROKER_HOSTS:"localhost:9092"}
                                            configuration:
                                                security:
                                                    protocol: ${KAFKA_PROTOCOL:SASL_PLAINTEXT}
                                                sasl:
                                                    mechanism: PLAIN
                                                    jaas:
                                                        config: "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"order-api\" password=\"order-api\";"

# OPEN API CONFIGURATION
springdoc:
    api-docs:
        path: /api-docs
        resolve-schema-properties: true
    override-with-generic-response: false
    paths-to-exclude: /**/api-docs,/swagger-resources/**
    swagger-ui:
        path: /

# LOGGING CONFIGURATION
logging:
    level:
        ROOT: INFO
        com.resilience: INFO
    appender: CONSOLE
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss.SSS} TraceId: %X{trace_id} SpanId: %X{span_id} %highlight(%-5level) %magenta([%t]) %msg%n"

# CIRCUIT BREAKER CONFIGURATION
resilience4j:
    circuitbreaker:
        configs:
            default:
                registerHealthIndicator: true
                failureRateThreshold: 50
                slowCallRateThreshold: 50
                slowCallDurationThreshold: 5s
                permittedNumberOfCallsInHalfOpenState: 3
                slidingWindowType: COUNT_BASED
                slidingWindowSize: 10
                minimumNumberOfCalls: 5
                waitDurationInOpenState: 30s
        instances:
            authorizationCircuitBreaker:
                base-config: default

# BULKHEAD CONFIGURATION
    bulkhead:
        instances:
            authorizationBulkhead:
                registerHealthIndicator: true
                maxConcurrentCalls: 10
                maxWaitDuration: 100ms

# RATE LIMITER CONFIGURATION
    ratelimiter:
        instances:
            getOrderByIdRateLimiter:
                registerHealthIndicator: true
                limitForPeriod: 10
                limitRefreshPeriod: 30s
                timeoutDuration: 100ms

# APPLICATION CONFIGURATION
application:
    clients:
        authorization:
            base-url: ${AUTHORIZATION_CLIENT_BASE_URL:http://localhost:8081}
